### ISSUE TITLE
Cannot use before/after in ConditionSet

### ISSUE THREAD

**Issue by cBournhonesque** [IyesGames/iyes_loopless#44]
I don't know if it's expected, but it looks like we cannot use the `before/after` functions inside a condition set?

If i try to run
```
.add_system_set(
                ConditionSet::new()
                    .run_in_state(InGameState::Game)
                    .with_system(food_contact_event)
                    .with_system(grow_snake_event.after(food_contact_event))
                    .into()
            );
```

I get the error:
```
the trait `IntoSystem<(), (), _>` is not implemented for `SystemDescriptor`

631 |         S: AddConditionalToSet<ConditionSystemSet, P>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `ConditionSystemSet::with_system`
```

Looks like it's because some trait bounds are missing?

Maybe i'm approaching things incorrectly and there's a different way to do this.

**Comment by inodentry** [comment]
Yes, this is a very commonly encountered issue with ConditionSet, because you and other people (understandably) expect it to work like SystemSet.

However, it is not possible to implement this syntax, because various Bevy ECS internals are not `pub`, so I cannot access them from `iyes_loopless`.

ConditionSet is only capable of applying the same labels and ordering to all of its member systems. If any system needs anything different, for now the workaround is to pull it out of the ConditionSet and add it separately.
